# NumPy Tricks: Specialized Utility Functions

Welcome to NumPy Tricks! This module covers specialized functions that solve specific data manipulation problems efficiently.

These aren't "tricks" in the magic sense - they're powerful utilities that every data scientist should know!

In [1]:
import numpy as np
import time

print("NumPy Tricks Module Ready")
print(f"NumPy version: {np.__version__}")

NumPy Tricks Module Ready
NumPy version: 2.4.2


## 1. np.sort & np.argsort: Sorting Magic

Sorting is one of the most common data manipulation tasks.

### Functions:
- `np.sort()` - Return sorted copy
- `np.argsort()` - Return indices that would sort the array

### Why Important:
- Ranking data (Top 10, Bottom 5)
- Finding medians and percentiles
- Organizing results for presentation
- Data preprocessing for ML algorithms

In [2]:
# REAL-WORLD EXAMPLE: Game Leaderboard Ranking
print("REAL-WORLD EXAMPLE: Game Leaderboard")
print("="*50)

players = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'])
scores = np.array([1500, 2300, 1800, 1600, 2100, 1900])

print("Players and scores:")
for player, score in zip(players, scores):
    print(f"  {player}: {score}")

# Get sorted indices (descending)
sorted_indices = np.argsort(-scores)  # Negative for descending
print("\nLeaderboard (sorted by score):")
for rank, idx in enumerate(sorted_indices, 1):
    print(f"  #{rank}: {players[idx]} - {scores[idx]} points")

# Get top 3
top_3_indices = sorted_indices[:3]
print(f"\nTop 3 players: {', '.join(players[top_3_indices])}")

REAL-WORLD EXAMPLE: Game Leaderboard
Players and scores:
  Alice: 1500
  Bob: 2300
  Charlie: 1800
  David: 1600
  Eve: 2100
  Frank: 1900

Leaderboard (sorted by score):
  #1: Bob - 2300 points
  #2: Eve - 2100 points
  #3: Frank - 1900 points
  #4: Charlie - 1800 points
  #5: David - 1600 points
  #6: Alice - 1500 points

Top 3 players: Bob, Eve, Frank


In [3]:
# Sorting arrays
data = np.array([34, 12, 87, 5, 56, 23, 91, 3])
print("Original data:", data)
print("Sorted:", np.sort(data))
print("Sorted descending:", np.sort(data)[::-1])

# Argsort: Get indices
sorted_indices = np.argsort(data)
print("\nIndices that sort array:", sorted_indices)
print("Using indices to access: data[argsort]:", data[sorted_indices])

# 2D sorting (sort by column)
data_2d = np.array([[3, 100], [1, 250], [2, 200]]) 
print("\n2D data (ID, Value):")
print(data_2d)
sorted_2d = data_2d[np.argsort(data_2d[:, 1])]  # Sort by value column
print("\nSorted by value:")
print(sorted_2d)

Original data: [34 12 87  5 56 23 91  3]
Sorted: [ 3  5 12 23 34 56 87 91]
Sorted descending: [91 87 56 34 23 12  5  3]

Indices that sort array: [7 3 1 5 0 4 2 6]
Using indices to access: data[argsort]: [ 3  5 12 23 34 56 87 91]

2D data (ID, Value):
[[  3 100]
 [  1 250]
 [  2 200]]

Sorted by value:
[[  3 100]
 [  2 200]
 [  1 250]]


## 2. np.unique: Finding Distinct Values

np.unique removes duplicates and finds distinct values.

### Features:
- Remove duplicates
- Return sorted unique values
- Optional: return indices, counts

### Use Cases:
- Data quality: Find unique categories
- Deduplication
- Value distribution analysis
- Group identification

In [4]:
# REAL-WORLD EXAMPLE: Data Quality Assessment
print("REAL-WORLD EXAMPLE: Customer Data Quality")
print("="*50)

# Customer data with potential duplicates
customer_ids = np.array([101, 102, 103, 101, 104, 102, 105, 103, 101])
countries = np.array(['USA', 'UK', 'US', 'USA', 'Canada', 'UK', 'USA', 'US', 'USA'])

print("Raw customer IDs:", customer_ids)
print("Raw countries:", countries)

# Find unique customers
unique_ids = np.unique(customer_ids)
print(f"\nUnique customers: {len(unique_ids)}")
print(f"IDs: {unique_ids}")

# Find unique countries with counts
unique_countries, counts = np.unique(countries, return_counts=True)
print(f"\nCountry distribution:")
for country, count in zip(unique_countries, counts):
    print(f"  {country}: {count}")

# Find duplicate customers
unique_ids_all, indices = np.unique(customer_ids, return_index=True)
dupes = customer_ids[~np.isin(np.arange(len(customer_ids)), indices)]
unique_dupes = np.unique(dupes)
print(f"\nDuplicate customer IDs: {unique_dupes}")

REAL-WORLD EXAMPLE: Customer Data Quality
Raw customer IDs: [101 102 103 101 104 102 105 103 101]
Raw countries: ['USA' 'UK' 'US' 'USA' 'Canada' 'UK' 'USA' 'US' 'USA']

Unique customers: 5
IDs: [101 102 103 104 105]

Country distribution:
  Canada: 1
  UK: 2
  US: 2
  USA: 4

Duplicate customer IDs: [101 102 103]


In [5]:
# Unique values demonstration
data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
print("Data with duplicates:", data)

unique_vals = np.unique(data)
print("Unique values:", unique_vals)

# Get counts
unique_vals, counts = np.unique(data, return_counts=True)
print("\nValue distribution:")
for val, count in zip(unique_vals, counts):
    print(f"  Value {val}: appears {count}x")

Data with duplicates: [1 2 2 3 3 3 4 4 4 4]
Unique values: [1 2 3 4]

Value distribution:
  Value 1: appears 1x
  Value 2: appears 2x
  Value 3: appears 3x
  Value 4: appears 4x


## 3. np.where: Conditional Selection & Assignment

np.where is a vectorized if-else statement. Extremely powerful for conditional operations.

### Syntax:
```python
np.where(condition, value_if_true, value_if_false)
```

### Use Cases:
- Conditional value replacement
- Alert systems (flag when condition met)
- Data cleaning (replace outliers)
- Classification (create categories)

In [6]:
# REAL-WORLD EXAMPLE: Alert System
print("REAL-WORLD EXAMPLE: Temperature Alert System")
print("="*50)

# Temperature readings from sensors
temps = np.array([22.1, 25.3, 18.9, 26.7, 24.2, 27.1, 23.8, 28.5, 20.1])
sensor_names = np.array(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9'])

print("Temperature readings:")
for sensor, temp in zip(sensor_names, temps):
    print(f"  {sensor}: {temp}°C")

# Alert if temp > 26°C
alerts = np.where(temps > 26, 'ALERT', 'OK')
print("\nTemperature status:")
for sensor, alert in zip(sensor_names, alerts):
    print(f"  {sensor}: {alert}")

# Severity classification
severity = np.where(temps < 20, 'COLD',
                    np.where(temps > 27, 'HOT', 'NORMAL'))
print("\nTemperature severity:")
for sensor, sev in zip(sensor_names, severity):
    print(f"  {sensor}: {sev}")

REAL-WORLD EXAMPLE: Temperature Alert System
Temperature readings:
  S1: 22.1°C
  S2: 25.3°C
  S3: 18.9°C
  S4: 26.7°C
  S5: 24.2°C
  S6: 27.1°C
  S7: 23.8°C
  S8: 28.5°C
  S9: 20.1°C

Temperature status:
  S1: OK
  S2: OK
  S3: OK
  S4: ALERT
  S5: OK
  S6: ALERT
  S7: OK
  S8: ALERT
  S9: OK

Temperature severity:
  S1: NORMAL
  S2: NORMAL
  S3: COLD
  S4: NORMAL
  S5: NORMAL
  S6: HOT
  S7: NORMAL
  S8: HOT
  S9: NORMAL


In [7]:
# np.where examples
data = np.array([1, 5, 3, 8, 2, 9, 4])
print("Original data:", data)

# Replace values > 5 with 0
result = np.where(data > 5, 0, data)
print("Replace > 5 with 0:", result)

# Create categories
categories = np.where(data > 5, 'Large', 'Small')
print("Categories:", categories)

# Find indices where condition is true
indices = np.where(data > 3)
print(f"\nIndices where > 3: {indices[0]}")
print(f"Values at those indices: {data[indices]}")

Original data: [1 5 3 8 2 9 4]
Replace > 5 with 0: [1 5 3 0 2 0 4]
Categories: ['Small' 'Small' 'Small' 'Large' 'Small' 'Large' 'Small']

Indices where > 3: [1 3 5 6]
Values at those indices: [5 8 9 4]


## 4. np.expand_dims: Adding Dimensions

Reshape data by adding new dimensions of size 1. Essential for broadcasting and ML pipelines.

### Why Needed:
- Prepare single sample for batch processing
- Match tensor dims for neural networks
- Enable broadcasting in calculations

In [8]:
# Expand dimensions
arr_1d = np.array([1, 2, 3])
print("1D array shape:", arr_1d.shape)  # (3,)

arr_2d = np.expand_dims(arr_1d, axis=0)  # Add dimension at front
print("After expand_dims(axis=0) shape:", arr_2d.shape)  # (1, 3)
print(arr_2d)

arr_2d_v2 = np.expand_dims(arr_1d, axis=1)  # Add dimension at end
print("\nAfter expand_dims(axis=1) shape:", arr_2d_v2.shape)  # (3, 1)
print(arr_2d_v2)

# ML example: prepare single image for batch processing
single_image = np.arange(9).reshape(3, 3)  # Shape: (3, 3)
print("\nSingle image shape:", single_image.shape)

batch = np.expand_dims(single_image, axis=0)  # Add batch dim
print("Batch with 1 image shape:", batch.shape)  # (1, 3, 3)
print(batch)

1D array shape: (3,)
After expand_dims(axis=0) shape: (1, 3)
[[1 2 3]]

After expand_dims(axis=1) shape: (3, 1)
[[1]
 [2]
 [3]]

Single image shape: (3, 3)
Batch with 1 image shape: (1, 3, 3)
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


## 5. np.select: Multiple Conditions

When np.where gets nested and messy, use np.select for multiple conditions.

### Syntax:
```python
np.select(conditions, choices, default)
```

### Advantages:
- Cleaner than nested np.where
- Better performance
- More readable

In [9]:
# REAL-WORLD EXAMPLE: Student Grade Classification
print("REAL-WORLD EXAMPLE: Exam Grade Classification")
print("="*50)

scores = np.array([92, 45, 78, 65, 88, 72, 55, 95, 60, 82])
print("Test scores:", scores)

# Using nested np.where (messy)
grades_messy = np.where(scores >= 90, 'A',
                       np.where(scores >= 80, 'B',
                               np.where(scores >= 70, 'C',
                                       np.where(scores >= 60, 'D', 'F'))))
print("\nGrades (nested where):", grades_messy)

# Using np.select (cleaner)
conditions = [
    scores >= 90,
    scores >= 80,
    scores >= 70,
    scores >= 60
]
choices = ['A', 'B', 'C', 'D']
grades = np.select(conditions, choices, default='F')
print("Grades (np.select):", grades)

# Print detailed results
print("\nGrade report:")
for score, grade in zip(scores, grades):
    print(f"  Score {score}: Grade {grade}")

REAL-WORLD EXAMPLE: Exam Grade Classification
Test scores: [92 45 78 65 88 72 55 95 60 82]

Grades (nested where): ['A' 'F' 'C' 'D' 'B' 'C' 'F' 'A' 'D' 'B']
Grades (np.select): ['A' 'F' 'C' 'D' 'B' 'C' 'F' 'A' 'D' 'B']

Grade report:
  Score 92: Grade A
  Score 45: Grade F
  Score 78: Grade C
  Score 65: Grade D
  Score 88: Grade B
  Score 72: Grade C
  Score 55: Grade F
  Score 95: Grade A
  Score 60: Grade D
  Score 82: Grade B


## 6. np.searchsorted: Binary Search

Find insertion positions in sorted arrays. Efficient for finding ranges and bins.

### Use Cases:
- Range queries (find values in interval)
- Binning data
- Percentile calculations
- Bucketing data

In [10]:
# Binary search with searchsorted
sorted_data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("Sorted data:", sorted_data)

# Find where values would be inserted
values_to_insert = np.array([15, 35, 65, 95])
positions = np.searchsorted(sorted_data, values_to_insert)
print(f"\nInsertion positions for {values_to_insert}:")
print(f"  Positions: {positions}")

# Find range: count values in interval [25, 75)
left = np.searchsorted(sorted_data, 25)
right = np.searchsorted(sorted_data, 75)
values_in_range = sorted_data[left:right]
print(f"\nValues in range [25, 75): {values_in_range}")

Sorted data: [10 20 30 40 50 60 70 80 90]

Insertion positions for [15 35 65 95]:
  Positions: [1 3 6 9]

Values in range [25, 75): [30 40 50 60 70]


## 7. np.histogram: Data Binning

Group continuous data into bins/buckets. Essential for exploratory data analysis.

### Returns:
- Counts: number of values in each bin
- Bin edges: boundaries of bins

### Use Cases:
- Distribution analysis
- Creating features for ML
- Data summarization

In [11]:
# REAL-WORLD EXAMPLE: Website Response Time Analysis
print("REAL-WORLD EXAMPLE: Website Performance Buckets")
print("="*50)

# Response times in milliseconds
response_times = np.array([45, 120, 89, 200, 67, 150, 95, 180, 55, 110, 75, 160, 90, 210, 130])
print(f"Response times: {response_times}")

# Create bins: fast (<100ms), medium (100-150ms), slow (>150ms)
bins = [0, 100, 150, 300]  # bin edges
counts, edges = np.histogram(response_times, bins=bins)

print("\nResponse time distribution:")
categories = ['Fast (<100ms)', 'Medium (100-150ms)', 'Slow (>150ms)']
for i, (cat, count) in enumerate(zip(categories, counts)):
    print(f"  {cat}: {count} requests")

# Calculate percentages
percentages = (counts / len(response_times)) * 100
print("\nPercentage distribution:")
for cat, pct in zip(categories, percentages):
    print(f"  {cat}: {pct:.1f}%")

REAL-WORLD EXAMPLE: Website Performance Buckets
Response times: [ 45 120  89 200  67 150  95 180  55 110  75 160  90 210 130]

Response time distribution:
  Fast (<100ms): 7 requests
  Medium (100-150ms): 3 requests
  Slow (>150ms): 5 requests

Percentage distribution:
  Fast (<100ms): 46.7%
  Medium (100-150ms): 20.0%
  Slow (>150ms): 33.3%


In [12]:
# Histogram examples
data = np.random.normal(100, 15, 1000)  # 1000 samples, mean=100, std=15
print(f"Data statistics: mean={np.mean(data):.1f}, std={np.std(data):.1f}")

# Create 10 equal-width bins
counts, bins = np.histogram(data, bins=10)
print(f"\nHistogram (10 bins):")
for i in range(len(counts)):
    print(f"  Bin [{bins[i]:.0f}-{bins[i+1]:.0f}): {counts[i]} values")

# Use percentile-based bins (quantiles)
quantile_bins = np.percentile(data, [0, 25, 50, 75, 100])
counts_q, _ = np.histogram(data, bins=quantile_bins)
print(f"\nPercentile-based bins:")
print(f"  Count per quartile: {counts_q}")

Data statistics: mean=98.9, std=14.6

Histogram (10 bins):
  Bin [57-65): 10 values
  Bin [65-73): 31 values
  Bin [73-82): 80 values
  Bin [82-90): 159 values
  Bin [90-98): 198 values
  Bin [98-106): 218 values
  Bin [106-115): 151 values
  Bin [115-123): 93 values
  Bin [123-131): 49 values
  Bin [131-139): 11 values

Percentile-based bins:
  Count per quartile: [250 250 250 250]


## 8. np.corrcoef: Correlation Analysis

Calculate correlation coefficients between variables.

### Returns:
- Correlation matrix: -1 to 1 (perfect negative to perfect positive)
- 0: no correlation

### Use Cases:
- Feature correlation analysis
- Collinearity detection
- Variable relationship study

In [13]:
# REAL-WORLD EXAMPLE: Student Performance Correlation
print("REAL-WORLD EXAMPLE: Study Hours vs Test Scores")
print("="*50)

# Student data
study_hours = np.array([2, 3, 5, 1, 4, 6, 2, 8, 3, 7])
test_scores = np.array([65, 72, 85, 55, 80, 92, 68, 95, 70, 88])
attendance = np.array([70, 80, 95, 60, 85, 100, 75, 98, 80, 92])  # percentage

print("Study hours:", study_hours)
print("Test scores:", test_scores)
print("Attendance %:", attendance)

# Calculate correlations
corr_study_scores = np.corrcoef(study_hours, test_scores)[0, 1]
corr_attend_scores = np.corrcoef(attendance, test_scores)[0, 1]

print(f"\nCorrelations with test scores:")
print(f"  Study hours: {corr_study_scores:.3f} (strong positive)")
print(f"  Attendance: {corr_attend_scores:.3f} (strong positive)")

# Full correlation matrix
data_matrix = np.array([study_hours, test_scores, attendance])
corr_matrix = np.corrcoef(data_matrix)
print("\nFull correlation matrix:")
print(np.round(corr_matrix, 3))

REAL-WORLD EXAMPLE: Study Hours vs Test Scores
Study hours: [2 3 5 1 4 6 2 8 3 7]
Test scores: [65 72 85 55 80 92 68 95 70 88]
Attendance %: [ 70  80  95  60  85 100  75  98  80  92]

Correlations with test scores:
  Study hours: 0.963 (strong positive)
  Attendance: 0.982 (strong positive)

Full correlation matrix:
[[1.    0.963 0.915]
 [0.963 1.    0.982]
 [0.915 0.982 1.   ]]


## Summary: When to Use Each Trick

| Function | Purpose | When to Use |
|----------|---------|-------------|
| `np.sort` | Sort values | Ranking, organizing data |
| `np.argsort` | Get sort indices | Get sorted positions, reorder related data |
| `np.unique` | Find distinct values | Deduplication, finding categories |
| `np.where` | Conditional assignment | Replace values, classify data |
| `np.select` | Multiple conditions | Complex categorization |
| `np.expand_dims` | Add dimension | Prepare for neural networks |
| `np.searchsorted` | Binary search | Range queries, efficient lookups |
| `np.histogram` | Bin data | Distribution analysis |
| `np.corrcoef` | Correlation | Feature analysis |

## Master List: Complete NumPy Journey

✅ **Completed Fundamentals**
- Array creation and structures
- Indexing and slicing
- Operations and functions
- Broadcasting
- Reshaping and stacking

✅ **Completed Advanced Topics**
- Complex indexing
- Linear algebra
- File I/O
- Performance optimization

✅ **Completed Specialized Utilities**
- Sorting and ranking
- Conditional operations
- Data binning
- Statistical analysis

## Final Recommendations

1. **Practice regularly** - Use real datasets
2. **Profile your code** - Measure performance
3. **Read NumPy docs** - Extensive and helpful
4. **Combine with Pandas** - For Data Science
5. **Explore SciPy** - For advanced science computing

You're now a NumPy expert! 🎉