# NumPy Advanced: Master Complex Operations

Welcome to NumPy Advanced! Here we dive deep into sophisticated techniques for data manipulation, linear algebra, and performance optimization.

**Prerequisites:** Complete NumPy Fundamentals first!

In [12]:
import numpy as np
import time
import sys

print("NumPy Advanced Module Loaded")
print(f"NumPy version: {np.__version__}")

NumPy Advanced Module Loaded
NumPy version: 2.4.2


## 1. Advanced Indexing: Boolean & Fancy Indexing

Advanced indexing goes beyond basic slicing. It enables sophisticated data selection and filtering.

### Types of Advanced Indexing:

**Boolean Indexing:**
- Use boolean arrays as masks
- Select elements where condition is True
- Can combine multiple conditions

**Fancy Indexing:**
- Use integer arrays to select specific indices
- Select rows/columns in arbitrary order
- Returns a copy, not a view

### Key Concepts:
- Boolean masks are created with comparison operators: `>`, `<`, `==`, `!=`, `&` (and), `|` (or), `~` (not)
- Multiple conditions combined with `&` (and) and `|` (or)
- Advanced indexing returns copies, not views

In [13]:
# REAL-WORLD EXAMPLE: E-Commerce Data Filtering
print("REAL-WORLD EXAMPLE: E-Commerce Order Filtering")
print("="*60)

# Order data: [order_id, amount, rating, is_delivery_delayed]
orders = np.array([
    [101, 250, 5, 0],   # Good order, on-time
    [102, 1500, 4, 1],  # Large order, delayed
    [103, 50, 1, 1],    # Small order, bad rating, delayed
    [104, 3000, 5, 0],  # Large order, excellent, on-time
    [105, 800, 2, 1],   # Medium order, poor rating, delayed
    [106, 120, 4, 0],   # Normal order, good rating, on-time
    [107, 2200, 3, 0],  # Large order, delayed
    [108, 45, 5, 0],    # Small order, excellent, on-time
])

print("All orders (amount, rating, delayed):")
print(orders)

# Boolean indexing: Find high-value orders
high_value = orders[:, 1] > 500  # Amount > 500
print(f"\nHigh-value orders (>500): {orders[high_value]}")

# Complex condition: Good rating AND not delayed
quality_orders = (orders[:, 2] >= 4) & (orders[:, 3] == 0)
print(f"\nQuality orders (rating >= 4 AND on-time):")
print(orders[quality_orders])

# Multiple conditions: Large orders OR delayed orders with poor ratings
problem_orders = (orders[:, 1] < 100) | ((orders[:, 3] == 1) & (orders[:, 2] < 2))
print(f"\nProblem orders (small order OR delayed+poor rating):")
print(orders[problem_orders])

REAL-WORLD EXAMPLE: E-Commerce Order Filtering
All orders (amount, rating, delayed):
[[ 101  250    5    0]
 [ 102 1500    4    1]
 [ 103   50    1    1]
 [ 104 3000    5    0]
 [ 105  800    2    1]
 [ 106  120    4    0]
 [ 107 2200    3    0]
 [ 108   45    5    0]]

High-value orders (>500): [[ 102 1500    4    1]
 [ 104 3000    5    0]
 [ 105  800    2    1]
 [ 107 2200    3    0]]

Quality orders (rating >= 4 AND on-time):
[[ 101  250    5    0]
 [ 104 3000    5    0]
 [ 106  120    4    0]
 [ 108   45    5    0]]

Problem orders (small order OR delayed+poor rating):
[[103  50   1   1]
 [108  45   5   0]]


In [14]:
# Fancy indexing: Select specific rows
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Original data:", data)

# Select specific indices
indices = np.array([0, 2, 5, 7])
selected = data[indices]
print(f"\nFancy indexing with indices {list(indices)}: {selected}")

# Use boolean mask
mask = data > 40
filtered = data[mask]
print(f"\nBoolean mask (> 40): {filtered}")

# Where condition is true
positions = np.where(mask)
print(f"Positions where > 40: {positions[0]}")

Original data: [10 20 30 40 50 60 70 80]

Fancy indexing with indices [np.int64(0), np.int64(2), np.int64(5), np.int64(7)]: [10 30 60 80]

Boolean mask (> 40): [50 60 70 80]
Positions where > 40: [4 5 6 7]


## 2. Broadcasting Deep Dive: Rules & Patterns

Broadcasting is powerful but can be confusing. Let's master the exact rules.

### Broadcasting Rules:

1. **Align from right**: Compare shapes from the rightmost dimension
2. **Dimension matching**: 
   - Dimensions must be equal, OR
   - One dimension must be 1
3. **Stretching**: Dimension of size 1 is stretched to match the other

### Examples:
```
Shape (3,4) + Shape (4,)     → (3,4) - (4,) stretched to (1,4) then (3,4)
Shape (3,1) + Shape (3,4)    → (3,1) stretched to (3,4)
Shape (3,4) + Shape (1,4)    → (1,4) stretched to (3,4)
Shape (3,4) + Shape (5,)     → ERROR - 4 and 5 don't match and neither is 1
```

In [15]:
# Broadcasting principles
print("BROADCASTING EXAMPLES")
print("="*50)

# Example 1: Row-wise operations
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_means = np.mean(data_2d, axis=1, keepdims=True)  # Shape (3, 1)
print("Data shape:", data_2d.shape)
print("Row means shape:", row_means.shape)
print("\nData:")
print(data_2d)
print("\nRow means (column vector):")
print(row_means)
print("\nData - Row means (broadcasts row_means to (3,3)):")
centered = data_2d - row_means
print(centered)

# Example 2: Scalar broadcasting
print("\nScalar broadcasting:")
scalar = 10
result = data_2d + scalar  # Scalar broadcasts to match (3,3)
print(f"Data + 10:")
print(result)

BROADCASTING EXAMPLES
Data shape: (3, 3)
Row means shape: (3, 1)

Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row means (column vector):
[[2.]
 [5.]
 [8.]]

Data - Row means (broadcasts row_means to (3,3)):
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]

Scalar broadcasting:
Data + 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


## 3. Linear Algebra: Matrix Operations

NumPy provides essential linear algebra operations. These are foundational for machine learning and scientific computing.

### Key Functions:

**Matrix Operations:**
- `np.dot()` - Matrix multiplication / dot product
- `np.matmul()` - Matrix multiplication (@operator)
- `np.transpose()` or `.T` - Transpose matrix
- `np.linalg.inv()` - Matrix inverse
- `np.linalg.det()` - Determinant

**Decomposition:**
- `np.linalg.eig()` - Eigenvalues & eigenvectors
- `np.linalg.svd()` - Singular Value Decomposition
- `np.linalg.qr()` - QR decomposition

**Solving Linear Systems:**
- `np.linalg.solve()` - Solve Ax = b

In [16]:
# REAL-WORLD EXAMPLE: Image Compression with SVD
print("REAL-WORLD EXAMPLE: Image Compression Concept")
print("="*50)

# Simulate a grayscale image as a matrix
np.random.seed(42)
image = np.random.randint(0, 256, (8, 8))  # 8x8 image
print("Original image (8x8):")
print(image)

# SVD decomposition
U, S, Vt = np.linalg.svd(image.astype(float))
print(f"\nSVD shapes: U={U.shape}, S={S.shape}, Vt={Vt.shape}")
print(f"Singular values: {np.round(S, 1)}")

# Keep only top 3 singular values for compression
k = 3
S_reduced = np.zeros_like(S)
S_reduced[:k] = S[:k]
image_compressed = U @ np.diag(S_reduced) @ Vt
print(f"\nCompressed image (keeping top {k} components):")
print(np.round(image_compressed, 1))

# Calculate compression ratio
original_size = image.size
compressed_size = (U[:, :k].size + k + Vt[:k, :].size)
print(f"\nOriginal data points: {original_size}")
print(f"Compressed data points: {compressed_size}")
print(f"Compression ratio: {compressed_size/original_size:.1%}")

REAL-WORLD EXAMPLE: Image Compression Concept
Original image (8x8):
[[102 179  92  14 106  71 188  20]
 [102 121 210 214  74 202  87 116]
 [ 99 103 151 130 149  52   1  87]
 [235 157  37 129 191 187  20 160]
 [203  57  21 252 235  88  48 218]
 [ 58 254 169 255 219 187 207  14]
 [189 189 174 189  50 107  54 243]
 [ 63 248 130 228  50 134  20  72]]

SVD shapes: U=(8, 8), S=(8,), Vt=(8, 8)
Singular values: [1094.   343.5  244.8  190.3  140.   117.7  105.    11.4]

Compressed image (keeping top 3 components):
[[ 47.9 145.   72.5  90.9 142.4  97.  144.6 -14.9]
 [104.2 195.6 179.8 211.2  75.5 147.1  64.3 121.2]
 [105.8 111.3  87.3 139.7  95.1  95.5  42.  104.4]
 [202.4 116.1  59.3 182.6 205.7 122.6  57.4 176.8]
 [239.4  87.6  32.1 185.6 226.4 115.4  31.5 217.5]
 [ 93.2 276.2 179.6 206.  202.  188.  215.5  22.5]
 [160.5 163.  164.9 236.4  79.3 143.7   6.6 202.7]
 [ 74.2 194.6 185.6 195.8  46.8 138.7  64.5  94.8]]

Original data points: 64
Compressed data points: 51
Compression ratio: 79.7%


In [17]:
# REAL-WORLD EXAMPLE: Image Compression with SVD
print("REAL-WORLD EXAMPLE: Image Compression with SVD")
print("="*60)

# Simulate a grayscale image as a matrix
np.random.seed(42)
image = np.random.randint(0, 256, (8, 8))  # 8x8 image
print("Original image (8x8):")
print(image)

# SVD decomposition
U, S, Vt = np.linalg.svd(image.astype(float))
print(f"\nSVD decomposition shapes:")
print(f"  U: {U.shape}  (left singular vectors)")
print(f"  S: {S.shape}  (singular values - importance of each component)")
print(f"  Vt: {Vt.shape} (right singular vectors)")
print(f"\nSingular values (sorted by importance): {np.round(S, 2)}")

# Keep only top k singular values for compression
k = 3  # Use only 3 out of 8 components
print(f"\n--- Compression: Keep only top {k} components ---")

# Create compressed image: U * diag(S_k) * Vt
S_reduced = np.zeros_like(S)
S_reduced[:k] = S[:k]  # Keep only top k singular values
image_compressed = U @ np.diag(S_reduced) @ Vt

print(f"Compressed image (reconstructed):")
print(np.round(image_compressed, 1))

# Calculate accurate compression ratio
# For SVD compression, we store: U[:, :k], S[:k], Vt[:k, :]
original_elements = image.size  # 8*8 = 64
# Components to store:
# - U[:, :k]:  8 rows × 3 cols = 24 elements
# - S[:k]:     3 elements
# - Vt[:k, :]: 3 rows × 8 cols = 24 elements
compressed_elements = (8 * k) + k + (k * 8)

print(f"\n--- Storage Analysis ---")
print(f"Original image: {original_elements} elements (8×8)")
print(f"Compressed components:")
print(f"  - U[:, :3] (8×3): {8*k} elements")
print(f"  - S[:3]:          {k} elements")
print(f"  - Vt[:3, :] (3×8): {k*8} elements")
print(f"Total compressed: {compressed_elements} elements")
print(f"\nCompression ratio: {compressed_elements}/{original_elements} = {compressed_elements/original_elements:.1%}")
print(f"Space saved: {100 - (compressed_elements/original_elements)*100:.1f}% reduction")

# Reconstruction error
reconstruction_error = np.mean((image - image_compressed)**2)
print(f"\nReconstruction quality: MSE = {reconstruction_error:.2f}")
print("Note: Using more components improves quality but reduces compression")

REAL-WORLD EXAMPLE: Image Compression with SVD
Original image (8x8):
[[102 179  92  14 106  71 188  20]
 [102 121 210 214  74 202  87 116]
 [ 99 103 151 130 149  52   1  87]
 [235 157  37 129 191 187  20 160]
 [203  57  21 252 235  88  48 218]
 [ 58 254 169 255 219 187 207  14]
 [189 189 174 189  50 107  54 243]
 [ 63 248 130 228  50 134  20  72]]

SVD decomposition shapes:
  U: (8, 8)  (left singular vectors)
  S: (8,)  (singular values - importance of each component)
  Vt: (8, 8) (right singular vectors)

Singular values (sorted by importance): [1094.03  343.54  244.82  190.3   140.05  117.71  104.96   11.38]

--- Compression: Keep only top 3 components ---
Compressed image (reconstructed):
[[ 47.9 145.   72.5  90.9 142.4  97.  144.6 -14.9]
 [104.2 195.6 179.8 211.2  75.5 147.1  64.3 121.2]
 [105.8 111.3  87.3 139.7  95.1  95.5  42.  104.4]
 [202.4 116.1  59.3 182.6 205.7 122.6  57.4 176.8]
 [239.4  87.6  32.1 185.6 226.4 115.4  31.5 217.5]
 [ 93.2 276.2 179.6 206.  202.  188.  215.5

## 4. File I/O: Reading & Writing Data

Working with files is essential for real-world data science.

### NumPy File I/O Functions:

**Binary Format (Fast, preserves dtypes):**
- `np.save()` - Save single array
- `np.load()` - Load single array
- `np.savez()` - Save multiple arrays
- `np.savez_compressed()` - Save compressed

**Text Format (Human-readable, universal):**
- `np.savetxt()` - Save as text/CSV
- `np.loadtxt()` - Load from text file
- `np.genfromtxt()` - Load with missing data handling

In [18]:
# File I/O demonstration
print("FILE I/O OPERATIONS")
print("="*50)

# Create sample data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original data:")
print(data)

# Save to binary format (fast)
np.save('/tmp/data_binary', data)
print("\n✓ Saved to /tmp/data_binary.npy")

# Load from binary
loaded = np.load('/tmp/data_binary.npy')
print("Loaded from binary:")
print(loaded)

# Save to text format (human-readable)
np.savetxt('/tmp/data.csv', data, delimiter=',')
print("\n✓ Saved to /tmp/data.csv")

# Load from text
loaded_text = np.loadtxt('/tmp/data.csv', delimiter=',')
print("Loaded from CSV:")
print(loaded_text)

FILE I/O OPERATIONS
Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

✓ Saved to /tmp/data_binary.npy
Loaded from binary:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

✓ Saved to /tmp/data.csv
Loaded from CSV:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 5. Working with Mathematical Formulas

NumPy enables implementing complex mathematical formulas efficiently.

### Common ML Formulas:

**Sigmoid Function** (used in logistic regression):
$$\sigma(x) = \frac{1}{1 + e^{-x}}$$

**Mean Squared Error** (regression loss):
$$MSE = \frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{y}_i)^2$$

**Softmax** (multiclass probability):
$$softmax(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

In [19]:
# REAL-WORLD EXAMPLE: ML Model Predictions
print("REAL-WORLD EXAMPLE: Neural Network Activation Functions")
print("="*60)

# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# ReLU (Rectified Linear Unit)
def relu(x):
    return np.maximum(0, x)

# Softmax
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Subtract max for numerical stability
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# Test data: logits from neural network
logits = np.array([
    [2.0, 1.0, 0.1],  # Sample 1
    [0.5, 3.0, 0.1],  # Sample 2
    [0.1, 0.1, 2.5]   # Sample 3
])

print("Network logits:")
print(logits)

probabilities = softmax(logits)
print("\nSoftmax probabilities:")
print(np.round(probabilities, 3))
print(f"\nProbabilities sum to 1 per sample: {np.sum(probabilities, axis=1)}")

# Predicted class
predictions = np.argmax(probabilities, axis=1)
print(f"Predicted classes: {predictions}")

REAL-WORLD EXAMPLE: Neural Network Activation Functions
Network logits:
[[2.  1.  0.1]
 [0.5 3.  0.1]
 [0.1 0.1 2.5]]

Softmax probabilities:
[[0.659 0.242 0.099]
 [0.072 0.879 0.048]
 [0.077 0.077 0.846]]

Probabilities sum to 1 per sample: [1. 1. 1.]
Predicted classes: [0 1 2]


In [20]:
# More mathematical functions
x = np.linspace(-5, 5, 10)
print("Input values:", np.round(x, 2))

print("\nSigmoid activation:")
print(np.round(sigmoid(x), 3))

print("\nReLU activation:")
print(np.round(relu(x), 2))

# Mean Squared Error
y_true = np.array([1, 2, 3])
y_pred = np.array([1.1, 1.9, 3.2])
mse = np.mean((y_true - y_pred) ** 2)
print(f"\nMean Squared Error: {mse:.4f}")

Input values: [-5.   -3.89 -2.78 -1.67 -0.56  0.56  1.67  2.78  3.89  5.  ]

Sigmoid activation:
[0.007 0.02  0.059 0.159 0.365 0.635 0.841 0.941 0.98  0.993]

ReLU activation:
[0.   0.   0.   0.   0.   0.56 1.67 2.78 3.89 5.  ]

Mean Squared Error: 0.0200


## 6. Performance Optimization

Understanding performance is crucial for working with large datasets.

### Optimization Techniques:

1. **Use appropriate dtypes**: int32 uses half memory of int64
2. **Vectorize instead of loop**: 100x faster or more
3. **Use views instead of copies**: Memory efficient
4. **Pre-allocate arrays**: Avoid repeated allocation
5. **Use built-in functions**: Implemented in C
6. **Consider memory layout**: C-order vs Fortran-order

### Measurement:
- Use `time.time()` for macro timing
- Use `np.timeit()` for micro timing
- Profile with `cProfile` for bottleneck identification

In [21]:
# PERFORMANCE COMPARISON
print("PERFORMANCE BENCHMARK: Real-World Optimizations")
print("="*60)

size = 1_000_000

# 1. Loop vs Vectorization (Core NumPy Advantage)
arr = np.arange(size)

# Slow: Python explicit loop
start = time.time()
result_loop = []
for x in arr:
    result_loop.append(x * 2 + 1)
time_loop = time.time() - start

# Fast: Vectorized NumPy
start = time.time()
result_vec = arr * 2 + 1
time_vec = time.time() - start

print(f"Loop implementation ({size:,} elements): {time_loop*1000:.2f} ms")
print(f"Vectorized NumPy: {time_vec*1000:.4f} ms")
print(f"Speedup: {time_loop/time_vec:.0f}x faster\n")
print(f"💡 Pro Tip: Always use vectorized operations over loops!\n")

# 2. Data type impact
arr_int64 = np.arange(size, dtype=np.int64)
arr_int32 = np.arange(size, dtype=np.int32)

print(f"Memory comparison:")
print(f"  int64 array: {arr_int64.nbytes / (1024**2):.1f} MB")
print(f"  int32 array: {arr_int32.nbytes / (1024**2):.1f} MB") 
print(f"  Savings: {(1 - arr_int32.nbytes/arr_int64.nbytes)*100:.0f}%\n")
print(f"💡 Pro Tip: Use int32 or float32 when range permits!\n")

# 3. In-place operations vs new arrays
arr = np.arange(100000)

start = time.time()
arr_new = arr * 2  # Creates new array
import sys
time_new = time.time() - start

start = time.time()
arr_inplace = arr.copy()
arr_inplace *= 2  # In-place operation
time_inplace = time.time() - start

print(f"New array creation: {time_new*1000:.4f} ms")
print(f"In-place operation: {time_inplace*1000:.4f} ms")
print(f"💡 Pro Tip: Use in-place ops (+=, *=) when possible to save memory!")

PERFORMANCE BENCHMARK: Real-World Optimizations
Loop implementation (1,000,000 elements): 231.34 ms
Vectorized NumPy: 6.0372 ms
Speedup: 38x faster

💡 Pro Tip: Always use vectorized operations over loops!

Memory comparison:
  int64 array: 7.6 MB
  int32 array: 3.8 MB
  Savings: 50%

💡 Pro Tip: Use int32 or float32 when range permits!

New array creation: 0.0000 ms
In-place operation: 0.0000 ms
💡 Pro Tip: Use in-place ops (+=, *=) when possible to save memory!


## 7. Real-World Project: Data Analysis Pipeline

Let's combine everything in a realistic data analysis scenario.

This example demonstrates:
- Loading data
- Advanced filtering
- Statistical analysis
- Linear regression
- Visualization insights

In [22]:
# INTEGRATED PROJECT: Stock Market Analysis
print("INTEGRATED PROJECT: Stock Market Analysis")
print("="*60)

np.random.seed(42)

# Simulate stock data: days, open, high, low, close, volume
days = 100
prices = np.cumsum(np.random.randn(days)) + 100  # Random walk from 100
volumes = np.random.randint(1000000, 10000000, days)
high_prices = prices + np.abs(np.random.randn(days)) * 2
low_prices = prices - np.abs(np.random.randn(days)) * 2

# Create data matrix
stock_data = np.column_stack((prices, high_prices, low_prices, volumes))
print(f"Stock data shape: {stock_data.shape}")
print("Columns: [Close, High, Low, Volume]")
print(f"\nFirst 5 days:")
print(np.round(stock_data[:5], 2))

# Analysis 1: Find high-volume trading days
median_volume = np.median(stock_data[:, 3])
high_volume_days = stock_data[:, 3] > (median_volume * 1.5)
print(f"\nHigh-volume days: {np.sum(high_volume_days)} out of {days}")

# Analysis 2: Calculate daily returns
returns = np.diff(prices) / prices[:-1] * 100
print(f"\nDaily Return Statistics:")
print(f"  Mean: {np.mean(returns):.3f}%")
print(f"  Std Dev: {np.std(returns):.3f}%")
print(f"  Max gain: {np.max(returns):.3f}%")
print(f"  Max loss: {np.min(returns):.3f}%")

# Analysis 3: Identify profitable trading days
profitable = returns > 0
print(f"\nProfitable days: {np.sum(profitable)} / {len(returns)} ({100*np.mean(profitable):.1f}%)")

# Analysis 4: Simple moving average
window = 10
sma = np.convolve(prices, np.ones(window)/window, mode='valid')
print(f"\nSimple Moving Average (window={window}):")
print(f"  Length: {len(sma)}")
print(f"  Last 5 values: {np.round(sma[-5:], 2)}")

INTEGRATED PROJECT: Stock Market Analysis
Stock data shape: (100, 4)
Columns: [Close, High, Low, Volume]

First 5 days:
[[1.005000e+02 1.031600e+02 1.004900e+02 2.954109e+06]
 [1.003600e+02 1.004100e+02 9.885000e+01 5.422880e+06]
 [1.010100e+02 1.036900e+02 9.714000e+01 8.205547e+06]
 [1.025300e+02 1.040000e+02 1.017000e+02 9.323735e+06]
 [1.023000e+02 1.042100e+02 1.011600e+02 7.457294e+06]]

High-volume days: 18 out of 100

Daily Return Statistics:
  Mean: -0.111%
  Std Dev: 0.965%
  Max gain: 1.976%
  Max loss: -2.787%

Profitable days: 45 / 99 (45.5%)

Simple Moving Average (window=10):
  Length: 91
  Last 5 values: [90.97 90.84 90.72 90.64 90.49]


## Summary: When to Use Advanced NumPy

### Advanced Indexing:
- When you need conditional element selection
- Data filtering with complex conditions
- Outlier detection and removal

### Broadcasting Deep Understanding:
- Implementing complex vectorized operations
- Debugging shape mismatch errors
- Optimizing memory usage

### Linear Algebra:
- Principal Component Analysis (PCA)
- Image compression
- Solving linear systems
- Machine learning algorithms

### File I/O:
- Loading/saving datasets
- Checkpointing models
- Data persistence

### Mathematical Formulas:
- Implementing ML algorithms
- Scientific computing
- Statistical analysis

### Performance Optimization:
- Working with large datasets (millions of elements)
- Production systems where speed matters
- Identifying real bottlenecks

## Next Steps:

→ **NumPy Tricks:** Specialized utility functions  
→ **Pandas:** Data manipulation and analysis  
→ **SciPy:** Advanced scientific computing  
→ **Machine Learning:** scikit-learn, TensorFlow, PyTorch

You're ready for professional data science work! 🚀