# NumPy Fundamentals: Complete Learning Guide

Welcome to the NumPy fundamentals course! This notebook introduces you to NumPy from scratch and builds a solid foundation in numerical computing with Python.

## 1. What is NumPy?

NumPy, short for Numerical Python, is the cornerstone library for scientific computing in Python. It provides a powerful N-dimensional array object called `ndarray`, which is the foundation for nearly all numerical computations in Python. NumPy arrays are homogeneous, meaning all elements must be of the same data type, which allows for efficient memory usage and fast operations.

### Key features of NumPy include:

- **Multidimensional Arrays**: Support for arrays of any dimension (1D, 2D, 3D, etc.), enabling complex data structures.

- **Mathematical Functions**: A vast collection of mathematical operations, from basic arithmetic to advanced functions like trigonometric, exponential, and logarithmic operations.

- **Broadcasting**: Automatic expansion of arrays to perform operations on arrays of different shapes.

- **Integration with Other Libraries**: Serves as the base for libraries like Pandas, SciPy, Matplotlib, and scikit-learn.

- **Performance**: Written in C, NumPy operations are much faster than equivalent Python list operations, especially for large datasets.

### Getting Started

To use NumPy, you first need to import it:

```python
import numpy as np
```

This convention is standard and allows you to access NumPy functions with the `np.` prefix.

In [19]:
import numpy as np
import sys
import time

print("NumPy imported successfully!")
print(f"NumPy version: {np.__version__}")

NumPy imported successfully!
NumPy version: 2.4.2


## 2. NumPy Arrays vs Python Sequences

NumPy arrays differ significantly from Python's built-in sequences like lists. Understanding these differences is crucial for efficient programming with NumPy.

### Key Differences:

| Aspect | NumPy Arrays | Python Lists |
|--------|--------------|---------------|
| **Size** | Fixed at creation | Dynamic (can grow/shrink) |
| **Data Types** | Homogeneous (all same type) | Heterogeneous (mixed types) |
| **Memory** | Contiguous, efficient | Scattered, overhead |
| **Speed** | 10-100x faster (C implementation) | Python loops are slow |
| **Operations** | Vectorized (no loops) | Element-wise loops needed |
| **Use Case** | Numerical computing | General data storage |

### When to Use NumPy Arrays:
- ✓ Working with numerical data
- ✓ Large datasets (thousands of elements or more)
- ✓ Scientific computing, data analysis, machine learning
- ✓ When performance is critical

### When to Use Python Lists:
- ✓ Small datasets with mixed types
- ✓ When dynamic sizing is needed
- ✓ General-purpose programming

## 3. Memory Efficiency & Vectorization: Why NumPy Matters

### The Problem with Python Lists:
Each element in a Python list is an independent Python object with significant overhead:
- **Memory per element**: ~50+ bytes (object reference, type info, reference count, value)
- **Speed cost**: Type checking and reference counting for every operation
- **Cache unfriendly**: Data scattered in memory (not contiguous)

### NumPy's Solution:
- **Memory per element**: Just the data type size (4-8 bytes for int32/float64)
- **Speed advantage**: Vectorized operations in C, no Python overhead
- **CPU friendly**: Contiguous memory = better cache performance

### Real-World Impact:
- **1 Million integers**: NumPy uses 4MB, Python uses 40+ MB (10x more!)
- **Speed**: NumPy is 10-100x faster than Python loops
- **Scalability**: With big data (millions of points), this saves both time and money

In [20]:
# DEMONSTRATION: Memory Comparison - CORRECTED
print("MEMORY COMPARISON: 1 Million Elements")
print("=" * 50)

size = 1_000_000

# Manual Python list memory calculation
# Each Python int object ~28 bytes + list overhead
python_list = list(range(size))
# Python list structure: ~56 bytes + 8 bytes per pointer
list_overhead = 56 + 8  
# Each Python integer object is typically 28 bytes
int_object_size = 28
list_total_memory = list_overhead + (size * int_object_size)

# NumPy array approach
numpy_array = np.arange(size, dtype=np.int64)
array_mem = numpy_array.nbytes

print(f"Python list (estimated): {list_total_memory / (1024**2):.1f} MB")
print(f"  Breakdown: {size:,} integers × 28 bytes each + overhead")
print(f"\nNumPy array (int64): {array_mem / (1024**2):.1f} MB")
print(f"  Breakdown: {size:,} integers × 8 bytes each")

memory_ratio = list_total_memory / array_mem
print(f"\n✓ NumPy uses {memory_ratio:.0f}x LESS memory!")
print(f"✓ Memory saved: {(list_total_memory - array_mem) / (1024**2):.1f} MB")

# Also try with int32 for even more savings
numpy_array_int32 = np.arange(size, dtype=np.int32)
print(f"\nNumPy array (int32): {numpy_array_int32.nbytes / (1024**2):.1f} MB")
print(f"✓ Using int32 saves an additional {(array_mem - numpy_array_int32.nbytes) / (1024**2):.1f} MB!")

MEMORY COMPARISON: 1 Million Elements
Python list (estimated): 26.7 MB
  Breakdown: 1,000,000 integers × 28 bytes each + overhead

NumPy array (int64): 7.6 MB
  Breakdown: 1,000,000 integers × 8 bytes each

✓ NumPy uses 4x LESS memory!
✓ Memory saved: 19.1 MB

NumPy array (int32): 3.8 MB
✓ Using int32 saves an additional 3.8 MB!


In [21]:
# DEMONSTRATION: Speed Comparison
print("\nSPEED COMPARISON: Adding Two Arrays")
print("=" * 50)

size = 100_000
small_list_a = list(range(size))
small_list_b = list(range(size, 2*size))

# Approach 1: Python loop (SLOW)
start = time.time()
result_loop = []
for i in range(len(small_list_a)):
    result_loop.append(small_list_a[i] + small_list_b[i])
time_loop = time.time() - start

# Approach 2: NumPy vectorized (FAST)
array_a = np.arange(size)
array_b = np.arange(size, 2*size)

start = time.time()
result_numpy = array_a + array_b
time_numpy = time.time() - start

print(f"Python loop on {size:,} elements: {time_loop*1000:.2f} ms")
print(f"NumPy vectorized on {size:,} elements: {time_numpy*1000:.4f} ms")
print(f"\n✓ NumPy is {time_loop/time_numpy:.0f}x FASTER!")
print(f"💡 Best Practice: Use vectorized operations instead of loops")
print(f"💡 With 1 million elements, NumPy saves ~{(time_loop/time_numpy):.0f}x the time!")


SPEED COMPARISON: Adding Two Arrays
Python loop on 100,000 elements: 18.12 ms
NumPy vectorized on 100,000 elements: 1.0004 ms

✓ NumPy is 18x FASTER!
💡 Best Practice: Use vectorized operations instead of loops
💡 With 1 million elements, NumPy saves ~18x the time!


## 4. Creating NumPy Arrays

NumPy provides several ways to create arrays. The most common method is using the `np.array()` function, which converts Python sequences into NumPy arrays.

### Array Creation Methods:

| Function | Purpose | Example |
|----------|---------|----------|
| `np.array()` | From Python list/tuple | `np.array([1, 2, 3])` |
| `np.arange()` | Evenly spaced values | `np.arange(0, 10, 2)` |
| `np.linspace()` | Specified number of evenly spaced values | `np.linspace(0, 1, 5)` |
| `np.ones()` | Array of ones | `np.ones((3, 4))` |
| `np.zeros()` | Array of zeros | `np.zeros((2, 5))` |
| `np.random.random()` | Random values [0, 1) | `np.random.random((2, 3))` |
| `np.identity()` | Identity matrix | `np.identity(4)` |

### Important: Data Types
You can specify `dtype` for memory efficiency: `np.int32`, `np.int64`, `np.float32`, `np.float64`

In [22]:
# REAL-WORLD EXAMPLE: Image Brightness Adjustment
print("REAL-WORLD EXAMPLE: Broadcasting in Image Processing")
print("="*50)

# Simulate RGB image: 3 color channels adjusted differently
image = np.array([
    [[100, 150, 200], [120, 160, 210]],  # Pixel 1, 2
    [[110, 155, 205], [130, 165, 215]]   # Pixel 3, 4
])
print(f"Image shape (rows, cols, RGB): {image.shape}")
print(f"Image:\n{image}")

# Adjust brightness: Multiply each channel by different factor
# Red channel × 1.0, Green × 1.1, Blue × 0.9
channel_multipliers = np.array([1.0, 1.1, 0.9])  # Shape: (3,)

# Broadcasting: image is (2, 2, 3), multiplier is (3,)
# NumPy automatically expands multiplier to (1, 1, 3) then (2, 2, 3)
brightened = image * channel_multipliers

print(f"\nChannel adjustments (RGB): {channel_multipliers}")
print(f"Broadcasted result:\n{brightened}")
print(f"\n💡 Best Practice: Broadcasting avoided explicit loops!")
print(f"💡 Without broadcasting: needed 3 nested loops (rows × cols × channels)")

REAL-WORLD EXAMPLE: Broadcasting in Image Processing
Image shape (rows, cols, RGB): (2, 2, 3)
Image:
[[[100 150 200]
  [120 160 210]]

 [[110 155 205]
  [130 165 215]]]

Channel adjustments (RGB): [1.  1.1 0.9]
Broadcasted result:
[[[100.  165.  180. ]
  [120.  176.  189. ]]

 [[110.  170.5 184.5]
  [130.  181.5 193.5]]]

💡 Best Practice: Broadcasting avoided explicit loops!
💡 Without broadcasting: needed 3 nested loops (rows × cols × channels)


## 5. Array Attributes

NumPy arrays have several important attributes that provide information about the array's structure and properties.

### Key Attributes:

| Attribute | Meaning | Example |
|-----------|---------|----------|
| `ndim` | Number of dimensions | 1D=1, 2D=2, 3D=3 |
| `shape` | Size of each dimension | (3, 4) for 3x4 matrix |
| `size` | Total number of elements | 3 × 4 = 12 |
| `dtype` | Element data type | int32, float64, etc. |
| `itemsize` | Size in bytes per element | 4 for int32, 8 for int64 |
| `nbytes` | Total bytes (size × itemsize) | 12 × 4 = 48 bytes |

These attributes help you understand your data structure and are crucial for indexing, slicing, and debugging.

In [23]:
# Create example arrays
a1 = np.arange(15, dtype=np.int32)  # 1D array
a2 = np.arange(20, dtype=float).reshape(4, 5)  # 2D array
a3 = np.arange(24).reshape(2, 3, 4)  # 3D array

print("1D Array a1:")
print(f"  Shape: {a1.shape}, Dimensions: {a1.ndim}, Size: {a1.size}")
print(f"  Data type: {a1.dtype}, Item size: {a1.itemsize}, Total bytes: {a1.nbytes}")

print("\n2D Array a2:")
print(a2)
print(f"  Shape: {a2.shape}, Dimensions: {a2.ndim}, Size: {a2.size}")
print(f"  Data type: {a2.dtype}, Total bytes: {a2.nbytes}")

print("\n3D Array a3:")
print(f"  Shape: {a3.shape}, Dimensions: {a3.ndim}, Size: {a3.size}")

1D Array a1:
  Shape: (15,), Dimensions: 1, Size: 15
  Data type: int32, Item size: 4, Total bytes: 60

2D Array a2:
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
  Shape: (4, 5), Dimensions: 2, Size: 20
  Data type: float64, Total bytes: 160

3D Array a3:
  Shape: (2, 3, 4), Dimensions: 3, Size: 24


## 6. Indexing & Slicing: Accessing Array Elements

Indexing and slicing allow you to access and modify specific elements, rows, columns, or subarrays. This is **fundamental** for data manipulation.

### Basic Indexing Syntax:

**1D Array:**
```python
arr[0]      # First element
arr[-1]     # Last element
arr[2:5]    # Elements 2, 3, 4 (stop is exclusive)
arr[::2]    # Every other element
```

**2D Array:**
```python
arr[0]         # First row
arr[0, :]      # First row (explicit)
arr[:, 0]      # First column
arr[1:3, 2:4]  # Subarray: rows 1-2, columns 2-3
```

### Important Concepts:
- **0-indexed**: First element is at index 0
- **Negative indices**: -1 means last element
- **Views vs Copies**: Slicing returns views (references), not copies
- **Colon syntax**: `:` means "all elements along this axis"

In [24]:
# REAL-WORLD EXAMPLE: Student Grade Analysis
print("REAL-WORLD EXAMPLE: Student Grade Analysis")
print("="*50)

# Student grades in 3 exams
grades = np.array([
    [85, 90, 78],  # Student 1
    [92, 88, 95],  # Student 2
    [75, 82, 80],  # Student 3
    [88, 91, 87],  # Student 4
    [78, 75, 72]   # Student 5
])

print("All grades (5 students, 3 exams):")
print(grades)

print("\nStudent 2 grades:", grades[1])
print("First exam scores:", grades[:, 0])
print("Top 3 students:", grades[:3])
print("Last exam of last student:", grades[-1, -1])
print("Every other student:", grades[::2])

REAL-WORLD EXAMPLE: Student Grade Analysis
All grades (5 students, 3 exams):
[[85 90 78]
 [92 88 95]
 [75 82 80]
 [88 91 87]
 [78 75 72]]

Student 2 grades: [92 88 95]
First exam scores: [85 92 75 88 78]
Top 3 students: [[85 90 78]
 [92 88 95]
 [75 82 80]]
Last exam of last student: 72
Every other student: [[85 90 78]
 [75 82 80]
 [78 75 72]]


In [25]:
# Basic indexing with 1D array
arr_1d = np.arange(15)
print("1D Array:", arr_1d)
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])
print("Elements 2-5:", arr_1d[2:6])
print("Every other element:", arr_1d[::2])

# Slicing 2D array
arr_2d = np.arange(20).reshape(4, 5)
print("\n2D Array:")
print(arr_2d)
print("\nFirst row:", arr_2d[0])
print("\nFirst column:", arr_2d[:, 0])
print("\nSubarray [1:3, 2:4]:")
print(arr_2d[1:3, 2:4])

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
First element: 0
Last element: 14
Elements 2-5: [2 3 4 5]
Every other element: [ 0  2  4  6  8 10 12 14]

2D Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

First row: [0 1 2 3 4]

First column: [ 0  5 10 15]

Subarray [1:3, 2:4]:
[[ 7  8]
 [12 13]]


## 7. Changing Data Types

NumPy arrays have a fixed data type, but you can change it using the `astype()` method.

### Why Change Data Types?
- **Memory Efficiency**: `int32` uses half the memory of `int64`
- **Compatibility**: Convert to match function requirements
- **Precision**: Switch between float32 and float64

### Important Notes:
- `astype()` returns a NEW array (doesn't modify original)
- Converting float to int TRUNCATES decimals
- Smaller types may lose data (overflow)

In [26]:
# Data type conversion
float_arr = np.array([1.5, 2.7, 3.9, 4.2])
print("Original float array:", float_arr)
print("Data type:", float_arr.dtype)

# Convert to int (truncates decimals)
int_arr = float_arr.astype(np.int32)
print("\nConverted to int32:", int_arr)
print("Data type:", int_arr.dtype)

# Check memory difference
arr_64 = np.arange(100, dtype=np.int64)
arr_32 = arr_64.astype(np.int32)
print(f"\nint64 array uses {arr_64.nbytes} bytes")
print(f"int32 array uses {arr_32.nbytes} bytes (half the memory!)")

Original float array: [1.5 2.7 3.9 4.2]
Data type: float64

Converted to int32: [1 2 3 4]
Data type: int32

int64 array uses 800 bytes
int32 array uses 400 bytes (half the memory!)


## 8. Array Operations

NumPy provides powerful **element-wise** operations - applied to all elements without explicit loops.

### Types of Operations:

**Scalar Operations** (array with single number):
```python
arr * 2       # Multiply all elements by 2
arr + 10      # Add 10 to all elements
arr ** 2      # Square all elements
arr > 50      # Boolean comparison
```

**Vector Operations** (between two arrays):
```python
arr1 + arr2   # Element-wise addition
arr1 * arr2   # Element-wise multiplication (NOT matrix mult!)
arr1 / arr2   # Element-wise division
```

### Key Concept: Vectorization
All operations happen in compiled C code - MUCH faster than loops!

In [27]:
# REAL-WORLD EXAMPLE: Stock Price Returns
print("REAL-WORLD EXAMPLE: Stock Price Returns")
print("="*50)

# Closing prices for 5 days
prices = np.array([100.5, 102.3, 101.8, 103.2, 101.9])
print("Daily closing prices:", prices)

# Calculate daily returns (percentage change)
returns = ((prices[1:] - prices[:-1]) / prices[:-1]) * 100
print("Daily returns (%):", np.round(returns, 2))

# With scalar operations
prices_after_markup = prices * 1.02  # 2% markup
print("Prices after 2% markup:", np.round(prices_after_markup, 2))

# Boolean operations
trending_up = prices > 101
print("Days when price > 101:", trending_up)
print("Number of up days:", np.sum(trending_up))

REAL-WORLD EXAMPLE: Stock Price Returns
Daily closing prices: [100.5 102.3 101.8 103.2 101.9]
Daily returns (%): [ 1.79 -0.49  1.38 -1.26]
Prices after 2% markup: [102.51 104.35 103.84 105.26 103.94]
Days when price > 101: [False  True  True  True  True]
Number of up days: 4


In [28]:
# Array operations demo
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)

# Scalar operations
print("\na * 2:", a * 2)
print("a + 5:", a + 5)
print("a ** 2:", a ** 2)

# Vector operations
print("\na + b:", a + b)
print("a * b:", a * b)  # Element-wise, NOT dot product
print("b / a:", b / a)

# Boolean operations
print("\na > 2:", a > 2)
print("a == 3:", a == 3)

Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]

a * 2: [ 2  4  6  8 10]
a + 5: [ 6  7  8  9 10]
a ** 2: [ 1  4  9 16 25]

a + b: [11 22 33 44 55]
a * b: [ 10  40  90 160 250]
b / a: [10. 10. 10. 10. 10.]

a > 2: [False False  True  True  True]
a == 3: [False False  True False False]


## 9. Array Functions

NumPy provides a vast library of functions for mathematical and statistical operations on arrays.

### Statistical Functions:
```python
np.max()      # Maximum value
np.min()      # Minimum value
np.mean()     # Average
np.median()   # Middle value
np.std()      # Standard deviation
np.var()      # Variance
np.sum()      # Sum of elements
np.product()  # Product of elements
```

### Mathematical Functions:
```python
np.sin(), np.cos(), np.tan()    # Trigonometric
np.exp(), np.log(), np.log10()  # Exponential & logarithmic
np.sqrt(), np.square()           # Root & square
np.abs()                         # Absolute value
np.round(), np.floor(), np.ceil() # Rounding
```

### Important: axis Parameter
```python
np.sum(arr)         # Sum all elements
np.sum(arr, axis=0) # Sum along columns (when 2D)
np.sum(arr, axis=1) # Sum along rows (when 2D)
```

In [29]:
# REAL-WORLD EXAMPLE: Sensor Data Analysis
print("REAL-WORLD EXAMPLE: Sensor Data Analysis")
print("="*50)

# Temperature readings from 5 sensors (10 measurements each)
temps = np.array([
    [20.1, 20.5, 19.8, 20.2, 20.6],  # Sensor 1
    [21.2, 20.9, 21.5, 21.1, 20.8],  # Sensor 2
    [19.9, 20.1, 19.7, 20.0, 20.2],  # Sensor 3
    [22.1, 21.8, 22.3, 21.9, 22.0],  # Sensor 4
    [20.5, 20.3, 20.7, 20.4, 20.6]   # Sensor 5
])

print("Temperature data (5 sensors, 5 measurements each):")
print(temps)

# Overall statistics
print(f"\nGlobal average: {np.mean(temps):.2f}°C")
print(f"Highest reading: {np.max(temps):.2f}°C")
print(f"Lowest reading: {np.min(temps):.2f}°C")
print(f"Standard deviation: {np.std(temps):.2f}°C")

# Per-sensor statistics
print("\nAverage per sensor:", np.round(np.mean(temps, axis=1), 2))
print("Min per sensor:", np.round(np.min(temps, axis=1), 2))
print("Max per sensor:", np.round(np.max(temps, axis=1), 2))

REAL-WORLD EXAMPLE: Sensor Data Analysis
Temperature data (5 sensors, 5 measurements each):
[[20.1 20.5 19.8 20.2 20.6]
 [21.2 20.9 21.5 21.1 20.8]
 [19.9 20.1 19.7 20.  20.2]
 [22.1 21.8 22.3 21.9 22. ]
 [20.5 20.3 20.7 20.4 20.6]]

Global average: 20.77°C
Highest reading: 22.30°C
Lowest reading: 19.70°C
Standard deviation: 0.76°C

Average per sensor: [20.24 21.1  19.98 22.02 20.5 ]
Min per sensor: [19.8 20.8 19.7 21.8 20.3]
Max per sensor: [20.6 21.5 20.2 22.3 20.7]


In [30]:
# Statistical functions demo
data = np.array([10, 25, 15, 30, 20, 18, 22, 28])
print("Data:", data)
print("\nStatistical Functions:")
print(f"  Max: {np.max(data)}")
print(f"  Min: {np.min(data)}")
print(f"  Mean: {np.mean(data):.1f}")
print(f"  Median: {np.median(data):.1f}")
print(f"  Std Dev: {np.std(data):.2f}")
print(f"  Sum: {np.sum(data)}")

# Mathematical functions
angles = np.array([0, 30, 45, 60, 90]) * np.pi / 180  # Convert to radians
print("\nTrigonometric Functions (for 0°, 30°, 45°, 60°, 90°):")
print(f"  sin: {np.round(np.sin(angles), 3)}")
print(f"  cos: {np.round(np.cos(angles), 3)}")

Data: [10 25 15 30 20 18 22 28]

Statistical Functions:
  Max: 30
  Min: 10
  Mean: 21.0
  Median: 21.0
  Std Dev: 6.26
  Sum: 168

Trigonometric Functions (for 0°, 30°, 45°, 60°, 90°):
  sin: [0.    0.5   0.707 0.866 1.   ]
  cos: [1.    0.866 0.707 0.5   0.   ]


## 10. Broadcasting: Automatic Shape Matching

Broadcasting is NumPy's powerful feature that allows operations between arrays of different shapes. NumPy automatically "broadcasts" smaller arrays to match larger ones.

### How Broadcasting Works:

When operating on two arrays, NumPy compares their shapes:
1. If dimensions are equal, proceed
2. If one dimension is 1, stretch it to match the other
3. If dimensions don't match and neither is 1, raise an error

### Real-World Examples:

**Example 1: Image Brightness**
- Image shape: (1080, 1920, 3) - RGB channels
- Multipliers: (3,) - one per channel
- Result: multipliers automatically broadcast to all pixels

**Example 2: Feature Normalization**
- Data: (1000, 50) - 1000 samples, 50 features
- Means: (50,) - one mean per feature
- Result: means broadcast to normalize all samples

In [31]:
# REAL-WORLD EXAMPLE 1: Image Brightness Adjustment
print("REAL-WORLD EXAMPLE 1: Image Brightness Adjustment")
print("="*60)

# Simulating a small image: height=4, width=5, channels=3 (RGB)
image = np.array([
    [[100, 150, 200], [110, 160, 210], [120, 170, 220], [130, 180, 230], [140, 190, 240]],
    [[105, 155, 205], [115, 165, 215], [125, 175, 225], [135, 185, 235], [145, 195, 245]],
    [[110, 160, 210], [120, 170, 220], [130, 180, 230], [140, 190, 240], [150, 200, 250]],
    [[115, 165, 215], [125, 175, 225], [135, 185, 235], [145, 195, 245], [155, 205, 255]]
], dtype=np.uint8)

print(f"Image shape: {image.shape}  (height=4, width=5, channels=3 RGB)")
print(f"Original image sample (first row, first 2 pixels):")
print(image[0, :2, :])

# Apply different multipliers per channel (R, G, B)
channel_multipliers = np.array([1.1, 1.0, 0.9])  # Boost R, keep G, reduce B (shape = (3,))
print(f"\nChannel multipliers (R, G, B): {channel_multipliers}")
print(f"Multiplier shape: {channel_multipliers.shape}")

# Broadcasting: (4,5,3) * (3,) -> automatically expands (3,) to match
brightened = (image.astype(float) * channel_multipliers).astype(np.uint8)
print(f"\nAfter brightness adjustment (first row, first 2 pixels):")
print(brightened[0, :2, :])
print(f"\n✓ Broadcasting applied multiplier to all {4*5}=20 pixels automatically!")
print(f"✓ No loops needed - this is vectorized and FAST!")

REAL-WORLD EXAMPLE 1: Image Brightness Adjustment
Image shape: (4, 5, 3)  (height=4, width=5, channels=3 RGB)
Original image sample (first row, first 2 pixels):
[[100 150 200]
 [110 160 210]]

Channel multipliers (R, G, B): [1.1 1.  0.9]
Multiplier shape: (3,)

After brightness adjustment (first row, first 2 pixels):
[[110 150 180]
 [121 160 189]]

✓ Broadcasting applied multiplier to all 20=20 pixels automatically!
✓ No loops needed - this is vectorized and FAST!


In [32]:
# REAL-WORLD EXAMPLE 2: Feature Normalization in Machine Learning
print("\nREAL-WORLD EXAMPLE 2: Feature Normalization for ML")
print("="*60)

# Sample student data: [Math Score, Physics Score, Chemistry Score]
# Scores are on very different scales!
features = np.array([
    [85, 90, 78],    # Student 1
    [92, 88, 85],    # Student 2
    [78, 95, 88],    # Student 3
    [88, 85, 92],    # Student 4
    [95, 92, 95]     # Student 5
])

print("Raw feature values (students × subjects):")
print(features)
print(f"\nFeature statistics:")
print(f"  Math: mean={np.mean(features[:, 0]):.1f}, std={np.std(features[:, 0]):.1f}")
print(f"  Physics: mean={np.mean(features[:, 1]):.1f}, std={np.std(features[:, 1]):.1f}")
print(f"  Chemistry: mean={np.mean(features[:, 2]):.1f}, std={np.std(features[:, 2]):.1f}")

# Calculate feature statistics per column (axis=0)
feature_means = np.mean(features, axis=0)    # Shape: (3,)
feature_stds = np.std(features, axis=0)      # Shape: (3,)

print(f"\nFeature means: {feature_means}")
print(f"Feature stds: {feature_stds}")

# Standardize: (x - mean) / std
# Broadcasting: features (5, 3) - means (3,) = (5, 3)
normalized = features - feature_means
standardized = normalized / feature_stds

print(f"\nStandardized features (z-score normalized):")
print(np.round(standardized, 3))

print(f"\n💡 Why normalize? Machine learning algorithms work better when:")
print(f"   - Features have zero mean and unit variance")
print(f"   - Features are on similar scales")
print(f"💡 Broadcasting magic: subtracted (3,) from (5,3), NumPy handled it!")
print(f"💡 Check: new mean ≈ 0: {np.round(np.mean(standardized, axis=0), 10)}")
print(f"💡 Check: new std ≈ 1: {np.round(np.std(standardized, axis=0), 10)}")


REAL-WORLD EXAMPLE 2: Feature Normalization for ML
Raw feature values (students × subjects):
[[85 90 78]
 [92 88 85]
 [78 95 88]
 [88 85 92]
 [95 92 95]]

Feature statistics:
  Math: mean=87.6, std=5.9
  Physics: mean=90.0, std=3.4
  Chemistry: mean=87.6, std=5.9

Feature means: [87.6 90.  87.6]
Feature stds: [5.88557559 3.40587727 5.88557559]

Standardized features (z-score normalized):
[[-0.442  0.    -1.631]
 [ 0.748 -0.587 -0.442]
 [-1.631  1.468  0.068]
 [ 0.068 -1.468  0.748]
 [ 1.257  0.587  1.257]]

💡 Why normalize? Machine learning algorithms work better when:
   - Features have zero mean and unit variance
   - Features are on similar scales
💡 Broadcasting magic: subtracted (3,) from (5,3), NumPy handled it!
💡 Check: new mean ≈ 0: [0. 0. 0.]
💡 Check: new std ≈ 1: [1. 1. 1.]


## 11. Reshaping: Changing Array Dimensions

Reshaping allows you to change array structure without changing data. Essential for preparing data for different algorithms.

### Key Functions:
- `reshape()` - Change dimensions (returns view)
- `transpose()` or `.T` - Swap rows and columns
- `ravel()` / `flatten()` - Convert to 1D array

### Important Rules:
- Total elements must stay the same: e.g., 24 elements can be (2,3,4) or (4,6) or (24,)
- Product of new dimensions must equal product of old dimensions

In [33]:
# Reshaping examples
arr_1d = np.arange(12)
print("Original 1D array:", arr_1d)
print("Shape:", arr_1d.shape)

# Reshape to 2D
arr_2d = arr_1d.reshape(3, 4)
print("\nReshaped to 3x4:")
print(arr_2d)

# Reshape to 3D
arr_3d = arr_1d.reshape(2, 2, 3)
print("\nReshaped to 2x2x3:")
print(arr_3d)

# Transpose
print("\nTransposed 3x4:")
print(arr_2d.T)
print("New shape:", arr_2d.T.shape)

# Flatten
flattened = arr_2d.ravel()
print("\nFlattened:", flattened)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x2x3:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Transposed 3x4:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
New shape: (4, 3)

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 12. Stacking & Combining Arrays

Stacking allows combining multiple arrays into one. Essential for building datasets from multiple sources.

### Stacking Functions:
- `vstack()` - Stack vertically (add rows)
- `hstack()` - Stack horizontally (add columns)
- `concatenate()` - More general stacking

### Requirements:
- Arrays must have compatible shapes
- For `vstack()`: same number of columns
- For `hstack()`: same number of rows

In [34]:
# REAL-WORLD EXAMPLE: Multi-Source Data Consolidation
print("REAL-WORLD EXAMPLE: Combining Monthly Sales Data")
print("="*50)

# Sales data from 3 stores for Month 1 and Month 2
month1_sales = np.array([
    [15000, 18000, 16500],  # Store A, B, C
    [20000, 19000, 18500]   # Product 1, 2
])

month2_sales = np.array([
    [16000, 19000, 17500],
    [21000, 20000, 19500]
])

print("Month 1 Sales (2 products, 3 stores):")
print(month1_sales)
print("\nMonth 2 Sales (2 products, 3 stores):")
print(month2_sales)

# Combine vertically (add months)
combined = np.vstack((month1_sales, month2_sales))
print("\nCombined (4 products, 3 stores):")
print(combined)
print(f"Combined shape: {combined.shape}")

# Calculate total per store
store_totals = np.sum(combined, axis=0)
print(f"\nTotal sales per store: {store_totals}")

REAL-WORLD EXAMPLE: Combining Monthly Sales Data
Month 1 Sales (2 products, 3 stores):
[[15000 18000 16500]
 [20000 19000 18500]]

Month 2 Sales (2 products, 3 stores):
[[16000 19000 17500]
 [21000 20000 19500]]

Combined (4 products, 3 stores):
[[15000 18000 16500]
 [20000 19000 18500]
 [16000 19000 17500]
 [21000 20000 19500]]
Combined shape: (4, 3)

Total sales per store: [72000 76000 72000]


In [35]:
# Stacking examples
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Array a:")
print(a)
print("\nArray b:")
print(b)

# Vertical stacking (add rows)
vstacked = np.vstack((a, b))
print("\nVertically stacked:")
print(vstacked)
print(f"Shape: {vstacked.shape}")

# Horizontal stacking (add columns)
hstacked = np.hstack((a, b))
print("\nHorizontally stacked:")
print(hstacked)
print(f"Shape: {hstacked.shape}")

Array a:
[[1 2]
 [3 4]]

Array b:
[[5 6]
 [7 8]]

Vertically stacked:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)

Horizontally stacked:
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)


## 13. Iterating Over Arrays

While NumPy encourages vectorized operations for performance, sometimes you need to iterate over elements.

### Iteration Methods:
- **Basic loop**: Simple iteration over rows (2D) or elements (1D)
- **np.nditer()**: Efficient element-wise iteration
- **enumerate()**: Get both index and value

### Important:
⚠️ **If you're iterating in NumPy, look for a vectorized alternative!** Iteration is slow compared to vectorized operations.

In [36]:
# Iteration examples
arr_1d = np.array([10, 20, 30, 40])
print("1D array:", arr_1d)
print("\nIterating:")
for val in arr_1d:
    print(f"  Value: {val}")

# 2D iteration (over rows)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:")
print(arr_2d)
print("\nIterating over rows:")
for i, row in enumerate(arr_2d):
    print(f"  Row {i}: {row}")

1D array: [10 20 30 40]

Iterating:
  Value: 10
  Value: 20
  Value: 30
  Value: 40

2D array:
[[1 2 3]
 [4 5 6]]

Iterating over rows:
  Row 0: [1 2 3]
  Row 1: [4 5 6]


## 14. Summary & Decision Guide

You've completed NumPy fundamentals! Here's when to use what:

### Array Creation:
| Task | Function | Example |
|------|----------|----------|
| From list | `np.array()` | `np.array([1,2,3])` |
| Evenly spaced | `np.arange()` | `np.arange(0, 10, 2)` |
| N points in range | `np.linspace()` | `np.linspace(0, 1, 5)` |
| All zeros | `np.zeros()` | `np.zeros((2,3))` |
| All ones | `np.ones()` | `np.ones((2,3))` |
| Random values | `np.random.random()` | `np.random.random((2,3))` |

### Data Access:
| Task | Syntax | Example |
|------|--------|----------|
| First element | `arr[0]` | Get first value |
| Last element | `arr[-1]` | Get last value |
| Range | `arr[start:end]` | `arr[2:5]` |
| Column (2D) | `arr[:, col_idx]` | `arr[:, 0]` |
| Row (2D) | `arr[row_idx]` | `arr[0]` |
| Subarray (2D) | `arr[r1:r2, c1:c2]` | `arr[1:3, 2:4]` |

### Operations:
| Task | Method |
|------|--------|
| Math operations | Use operators: `+`, `-`, `*`, `/` |
| Statistics | `np.mean()`, `np.std()`, `np.sum()` |
| Aggregation per axis | Use `axis=0` or `axis=1` parameter |
| Reshape | Use `reshape()`, `transpose()`, `ravel()` |
| Combine arrays | Use `vstack()`, `hstack()`, `concatenate()` |

### Performance Checklist:
- ✓ Use vectorized operations (NOT loops)
- ✓ Use appropriate data types (int32 vs int64)
- ✓ Leverage broadcasting for shape matching
- ✓ Use views instead of copying when possible
- ✓ Profile with large datasets to verify speed gains

## 15. Common Mistakes & Tips

### ⚠️ Common Mistakes to Avoid:

**Mistake 1: Using loops when vectorization is available**
```python
# ❌ SLOW - Don't do this
result = []
for x in arr:
    result.append(x * 2)

# ✓ FAST - Do this
result = arr * 2
```

**Mistake 2: Forgetting that arrays have fixed size**
```python
# ❌ Won't work - can't append to NumPy array
arr = np.array([1, 2, 3])
arr.append(4)  # ERROR!

# ✓ Use np.append() which returns new array
arr = np.append(arr, 4)
```

**Mistake 3: Modifying vs creating new array**
```python
arr1 = np.array([1, 2, 3])
arr2 = arr1          # arr2 points to arr1!
arr2[0] = 99         # This CHANGES arr1 too!

# ✓ Use copy() to create independent array
arr2 = arr1.copy()   # Now arr2 is separate
arr2[0] = 99         # arr1 unchanged
```

**Mistake 4: Data type mismatches**
```python
# ❌ int divided by int = int (loses decimal)
result = np.array([1, 2, 3], dtype=int) / 2  # [0, 1, 1] - truncated!

# ✓ Convert to float first
result = np.array([1, 2, 3], dtype=float) / 2  # [0.5, 1., 1.5]
```

**Mistake 5: Broadcasting confusion**
```python
# ❌ Shapes not compatible
a = np.array([[1, 2, 3]])      # Shape (1, 3)
b = np.array([[1], [2], [3]])  # Shape (3, 1)
result = a + b                 # Result is (3, 3)  - might not be what you expected!

# ✓ Be explicit about broadcasting
result = a.T + b               # Explicit and clear
```

### 💡 Pro Tips:

1. **Always check shape**: `arr.shape` before operations
2. **Print intermediate results**: Debug with `print()` while learning
3. **Use descriptive names**: `student_grades` instead of `data`
4. **Specify dtype explicitly**: Avoid surprises with data types
5. **Profile your code**: Use `time.time()` to verify speed improvements
6. **Read error messages carefully**: They usually tell you exactly what's wrong
7. **Slice instead of loop**: Look for vectorized alternatives
8. **Use axis parameter**: Often more efficient than manual loops

## 16. Next Steps

Congratulations! You've mastered NumPy fundamentals. You can now:

✓ Create and manipulate arrays of any shape
✓ Use vectorized operations for fast computation
✓ Apply broadcasting for elegant solutions
✓ Leverage NumPy's extensive function library
✓ Solve real-world problems with numerical data

### Continue Your Journey:

1. **Next: Advanced NumPy**
   - Advanced indexing (boolean, fancy)
   - Linear algebra operations
   - File I/O with NumPy
   - Performance optimization

2. **Practical Practice**
   - Work with real datasets
   - Implement mathematical algorithms
   - Build data processing pipelines

3. **Advanced Libraries**
   - Pandas for data manipulation
   - SciPy for scientific computing
   - Matplotlib for visualization
   - scikit-learn for machine learning

All of these build on NumPy, so your foundation is rock solid!

Happy coding! 🚀